### ISSUE TITLE
经常将左键单击识别为双击

### ISSUE THREAD

**Issue by Alan996** [indiff/qttabbar#247]
**描述这个Bug**
未经区分，以下点击均为鼠标左键。
安装qttabbar后，经常单击一个文件或文件夹会造成打开文件或打开文件的操作，甚至单击返回键会出现连返两级父目录！！！严重影响体验。系统版本如下：
![image](https://user-images.githubusercontent.com/41531958/186714416-a19fe014-1568-40b8-af19-883b4951e046.png)

**重现过程**
重现过程的步骤:
1. 安装qttabbar后
2. 打开任意文件夹
3. 重复多次进出某个文件夹，其中某几次单击文件夹，而不是双击
4. 会出现进入文件夹的bug。同样单击导航栏的返回键（win10自带），会出现连返两级父目录。
5. 偶现，概率20-30%

**期望的结构**
不会将单击识别为双击

**截图**
难以截图描述

**系统环境:**
![image](https://user-images.githubusercontent.com/41531958/186715292-a605b428-caa3-49c5-a52b-65f913d69d02.png)
qttabbar版本：
![image](https://user-images.githubusercontent.com/41531958/186715529-71b496e2-7143-4c01-b449-d45c18d17ade.png)

**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**
2022/8/25 1:03:28
.NET 版本: 2.0.50727.9164
操作系统版本: 10.0.19043.0
QT 版本: DevBuild: 2022/6/23 14:45:37 (2.0.50727.9164)
错误信息: Failed navigation: D:\MIUI\x\实况照片
Exception: None
   at System.Environment.get_StackTrace()
   at QTTabBarLib.QTUtility2.MakeErrorLog(Exception ex, String optional)
   at QTTabBarLib.QTTabBarClass.ShowMessageNavCanceled(String failedPath, Boolean fModal)
   at QTTabBarLib.QTTabBarClass.tabControl1_SelectedIndexChanged(Object sender, EventArgs e)
   at QTTabBarLib.QTabControl.ChangeSelection(QTabItem tabToSelect, Int32 index)
   at QTTabBarLib.QTabControl.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at QTTabBarLib.QTabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--------------

2022/8/25 1:32:09
.NET 版本: 2.0.50727.9164
操作系统版本: 10.0.19043.0
QT 版本: DevBuild: 2022/6/23 14:45:37 (2.0.50727.9164)
错误信息: Failed navigation: D:\MIUI
Exception: None
   at System.Environment.get_StackTrace()
   at QTTabBarLib.QTUtility2.MakeErrorLog(Exception ex, String optional)
   at QTTabBarLib.QTTabBarClass.ShowMessageNavCanceled(String failedPath, Boolean fModal)
   at QTTabBarLib.QTTabBarClass.tabControl1_SelectedIndexChanged(Object sender, EventArgs e)
   at QTTabBarLib.QTabControl.ChangeSelection(QTabItem tabToSelect, Int32 index)
   at QTTabBarLib.QTabControl.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at QTTabBarLib.QTabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--------------

**Comment by indiff** [comment]
这个应该是文件夹不被删除了， 或者加载不了的。 属于正常报错
