### ISSUE TITLE
Windows10 22H2 点击选项后崩溃

### ISSUE THREAD

**Issue by legical** [indiff/qttabbar#322]
**描述这个Bug**
点击选项后崩溃，文件资源管理器会自动重启

**重现过程**
重现过程的步骤:
1. 第一次点击 选项， 状态：卡住
2. 第二次点击 选项， 状态：程序崩溃，文件资源管理器自动重启

**期望的结构**
解决这个bug

**截图**
已安装.net 3.5

![](https://raw.githubusercontent.com/leegical/Blog_img/master/md_img202303272135333.png)

**系统环境:**
 - 操作系统: Windows10 22H2
 - .net framework: 3.5
 - 软件版本: v1.5.5-beta.9
 - 重点、重点、重点；没有报错日志本地复现不了的话，那这个问题不会处理
**上传报错日志(C:\Users\Administrator\AppData\Roaming\QTTabBar\QTTabBarException.log):**
```
[flog]	C:LangEntry	M:Reset	P:3364	T:5	cost:1.9988毫秒	2023/3/27 21:37:35	*** TextResourcesDic not contains key Version_LangFile
[flog]	C:LangEntry	M:Reset	P:19988	T:14	cost:1.9973毫秒	2023/3/27 21:39:26	*** TextResourcesDic not contains key Version_LangFile
```

**Comment by XingrunLi** [comment]
我也遇到了这个bug，每次点选项就崩溃

**Comment by Vyp3R** [comment]
Happening for me too. 

Just click QTTabBar's "Option" button, and Explorer self closes every time. Tabs are also lost.

QTTabBarException.log:
`9/02/2024 3:55:25 PM
.NET 版本: 4.0.30319.42000
操作系统版本: 10.0.19045.0 Major: 10 环境: 64
QT 版本: DevBuild: 15/02/2023 12:59:26 AM (4.0.30319.42000)
错误信息: OptionsDialog constructor

Message ---
Set connectionId threw an exception.
HelpLink ---

Source ---
PresentationFramework
StackTrace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at QTTabBarLib.OptionsDialog..ctor()
TargetSite ---
Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)****************InnnerExcetpion

  InnerMessage ---
[A]Ricciolo.Controls.TreeListView cannot be cast to [B]Ricciolo.Controls.TreeListView. Type A originates from 'Ricciolo.Controls.TreeListView, Version=1.1.0.0, Culture=neutral, PublicKeyToken=ffedd4b1334b06f5' in the context 'LoadNeither' in a byte array. Type B originates from 'Ricciolo.Controls.TreeListView, Version=1.1.0.0, Culture=neutral, PublicKeyToken=ffedd4b1334b06f5' in the context 'LoadNeither' in a byte array.
 InnerHelpLink ---

  InnerSource ---
QTTabBar
 InnerStackTrace ---
   at QTTabBarLib.Options10_Apps.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
 InnerTargetSite ---
Void System.Windows.Markup.IComponentConnector.Connect(Int32, System.Object)--------------`

**Comment by Vyp3R** [comment]
Seems to be a continuation of the problem here: [Issue #308](https://github.com/indiff/qttabbar/issues/308)
